### ISSUE TITLE
Complement the example with data creation

### ISSUE THREAD

**Issue by luistrigueiros** [neo4j-examples/neo4j-movies-java-bolt#2]
Dear @jexp,
I loved this example it is simple and elegant do you have and example of using the **_example.movies.executor.CypherExecutor_** to add data to the database ?
As this example is just reading data the 3 methods of the **_example.movies.backend.MovieService_** to only retrieval of data, can I use the **_CypherExecutor.query_** method also to insert data in the database ?

Thank you, kindly
  Luis Oscar

**Comment by fbiville** [comment]
Hi @luistrigueiros, I'm closing this issue, as `CypherExecutor` is now gone and we rely on the official Java driver directly.
