### ISSUE TITLE
 Cannot compile application

### ISSUE THREAD

**Issue by anhtv08** [neo4j-examples/neo4j-movies-java-bolt#3]
Dear folks,
I have downloaded applicaiton and tried to compiled it, I am facing with classNotFound Exception.

As below:

java.lang.ClassNotFoundException: example.jdbc.movies.MovieServer
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:285)
        at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.404 s
[INFO] Finished at: 2016-09-08T17:33:29+08:00
[INFO] Final Memory: 10M/24M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project neo4j-movies: An exception occured while executing the Java class. example.jdbc.movies.MovieServer -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

I have checked this class, but seems no such as class like this, MovieServer class belong to 
**example.movies.backend.MovieServer**.  

Appreciate for your promt action.

example.jdbc.movies.MovieServer

**Comment by jesantana** [comment]
+1

**Comment by jexp** [comment]
I just cloned and compiled it without problems.

mvn clean install
...

[INFO]

[INFO] --- maven-install-plugin:2.4:install (default-install) @
neo4j-movies ---

[INFO] Installing
/Users/mh/docs/examples/x/neo4j-movies-java-bolt/target/neo4j-movies-3.0-SNAPSHOT.jar
to
/Users/mh/.m2/repository/org/neo4j/example/neo4j-movies/3.0-SNAPSHOT/neo4j-movies-3.0-SNAPSHOT.jar

[INFO] Installing /Users/mh/docs/examples/x/neo4j-movies-java-bolt/pom.xml
to
/Users/mh/.m2/repository/org/neo4j/example/neo4j-movies/3.0-SNAPSHOT/neo4j-movies-3.0-SNAPSHOT.pom

[INFO]
------------------------------------------------------------------------

[INFO] BUILD SUCCESS

[INFO]
------------------------------------------------------------------------

[INFO] Total time: 5.378 s

[INFO] Finished at: 2016-09-09T00:49:32+02:00

[INFO] Final Memory: 36M/390M

[INFO]
------------------------------------------------------------------------

**Comment by netrebel** [comment]
@jexp This error happened when trying to run the application. `mvn install` worked fine. 
I submitted PR with this and other small fixes.
Regards.

**Comment by fbiville** [comment]
I believe this is not an issue anymore. Feel free to reopen the issue if it is.
